version: '3.1'

services:
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "8080:8080"
  couchdb:
    image: couchdb:3.2.2
    restart: on-failure
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: couchdb
      COUCHDB_PASSWORD: couchdb